package org.example.state;

public enum Status {
    IDLE, AWAITING_BUYER_NAME, AWAITING_FIRST_CURRENCY, AWAITING_SECOND_CURRENCY,  AWAITING_DEAL_AMOUNT, AWAITING_CUSTOM_APPROVE, AWAITING_EXCHANGE_RATE, AWAITING_APPROVE
}
