package org.example.state;

public enum Status {
    IDLE,
    AWAITING_BUYER_NAME,
    AWAITING_FIRST_CURRENCY,
    AWAITING_SECOND_CURRENCY,
    AWAITING_SELECT_AMOUNT,
    AWAITING_DEAL_AMOUNT,
    AWAITING_EXCHANGE_RATE_TYPE,
    AWAITING_CUSTOM_APPROVE,
    AWAITING_EXCHANGE_RATE,
    AWAITING_APPROVE
}
