package org.example.model.enums;

public enum Status {
    IDLE,
    AWAITING_BUYER_NAME,
    AWAITING_CHOOSE_BALANCE_FROM,
    AWAITING_CHOOSE_BALANCE_TO,
    AWAITING_CITY_NAME,
    AWAITING_COMMENT,
    AWAITING_PLUS_MINUS_TYPE,
    AWAITING_FIRST_CURRENCY,
    AWAITING_CHANGE_BALANCE_TYPE,
    AWAITING_SECOND_CURRENCY,
    AWAITING_SELECT_AMOUNT,
    AWAITING_AMOUNT_FOR_EACH_CURRENCY,
    AWAITING_AMOUNT_FOR_EACH_CURRENCY_FROM,
    AWAITING_AMOUNT_FOR_EACH_CURRENCY_TO,
    AWAITING_DEAL_AMOUNT,
    AWAITING_EXCHANGE_RATE_TYPE,
    AWAITING_CUSTOM_APPROVE,
    AWAITING_EXCHANGE_RATE,
    AWAITING_APPROVE,


    AWAITING_CURRENCY_TYPE
}
